server:
  port: 5000

spring:
  application:
    name: order-service
  datasource:
    url: jdbc:postgresql://localhost:5432/bd_pedido
    driver-class-name: org.postgresql.Driver
    username: postgres         
    password: 123
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true
  thymeleaf:
    prefix: classpath:/templates/
    suffix: .html
    mode: HTML
    encoding: UTF-8
    cache: false

logging:
  level:
    org.springframework.web: DEBUG
    org.hibernate.SQL: DEBUG
    org.hibernate.type.descriptor.sql.BasicBinder: TRACE

product-service:
  url: http://localhost:8080
