spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/bd_pedido
    username: postgres
    password: 123

  jpa:
    hibernate:
      ddl-auto: none
    database-platform: org.hibernate.dialect.PostgreSQLDialect